Import Required Libraries

In [24]:
import pandas as pd
import numpy as np

Load Dataset

In [25]:
df = pd.read_csv("/content/raw_crash_data.csv")

df.head()

,unique_id,case_id_fkey,latitude,longitude,collision_year,death_date,death_time,death_datetime,collision_date,collision_time,...,in_coc_2018,publish,on_vz_hin_2022,in_epa_2021,point,analysis_neighborhood,supervisor_district,police_district,data_as_of,data_loaded_at
0,1,140236301,37.710409,-122.404226,2014,2014/03/20,11:21:00,2014/03/20 11:21:00 AM,2014/03/20,NaN,...,False,True,True,False,POINT (-122.404226037 37.710409217),Bayview Hunters Point,10.0,INGLESIDE,2024/09/18 12:00:00 AM,2026/01/30 10:44:44 AM
1,2,140755533,37.725476,-122.394243,2014,2014/09/08,16:38:00,2014/09/08 04:38:00 PM,2014/09/08,05:10:00,...,True,True,True,True,POINT (-122.394243493 37.72547565),Bayview Hunters Point,10.0,BAYVIEW,2024/09/18 12:00:00 AM,2026/01/30 10:44:44 AM
2,4,140365546,37.748255,-122.413669,2014,2014/05/03,17:20:00,2014/05/03 05:20:00 PM,2014/05/03,02:24:00,...,False,True,True,False,POINT (-122.413668844 37.748255329),Mission,9.0,MISSION,2024/09/18 12:00:00 AM,2026/01/30 10:44:44 AM
3,16,150562049,37.777300,-122.419694,2015,2015/06/30,06:00:00,2015/06/30 06:00:00 AM,2015/06/28,03:52:00,...,False,True,True,True,POINT (-122.419693566 37.777299856),Tenderloin,5.0,NORTHERN,2024/09/18 12:00:00 AM,2026/01/30 10:44:44 AM
4,17,140104811,37.778251,-122.419883,2014,2014/02/06,10:20:00,2014/02/06 10:20:00 AM,2014/02/05,02:26:00,...,False,True,True,True,POINT (-122.419883231 37.778251017),Hayes Valley,5.0,NORTHERN,2024/09/18 12:00:00 AM,2026/01/30 10:44:44 AM

In [26]:
df.info()
df.describe()
df.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 351 entries, 0 to 350
Data columns (total 28 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   unique_id              351 non-null    int64
 1   case_id_fkey           344 non-null    object
 2   latitude               351 non-null    float64
 3   longitude              351 non-null    float64
 4   collision_year         351 non-null    int64
 5   death_date             351 non-null    object
 6   death_time             316 non-null    object
 7   death_datetime         351 non-null    object
 8   collision_date         351 non-null    object
 9   collision_time         326 non-null    object
 10  collision_datetime     351 non-null    object
 11  location               351 non-null    object
 12  age                    350 non-null    float64
 13  sex                    351 non-null    object
 14  deceased               351 non-null    object
 15  collision_type         351 non-null    object
 16  street_type            351 non-null    object
 17  on_vz_hin_2017         351 non-null    bool
 18  in_coc_2018            351 non-null    bool
 19  publish                351 non-null    bool
 20  on_vz_hin_2022         351 non-null    bool
 21  in_epa_2021            351 non-null    bool
 22  point                  351 non-null    object
 23  analysis_neighborhood  350 non-null    object
 24  supervisor_district    350 non-null    float64
 25  police_district        351 non-null    object
 26  data_as_of             350 non-null    object
 27  data_loaded_at         351 non-null    object
dtypes: bool(5), float64(4), int64(2), object(17)
memory usage: 64.9+ KB

(351, 28)

Data Cleaning

In [17]:
# Remove Unnecessary Columns
df.drop(columns=[
'unique_id',
'case_id_fkey',
'publish',
'point',
'data_loaded_at'
], inplace=True)

In [27]:
# Convert Date Columns
df['collision_datetime'] = pd.to_datetime(df['collision_datetime'])
df['death_datetime'] = pd.to_datetime(df['death_datetime'])

/tmp/ipykernel_166/2348409065.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['collision_datetime'] = pd.to_datetime(df['collision_datetime'])

Handle Missing Values

In [28]:
# Remove Rows with Missing Values
df = df.dropna(subset=[
'death_time',
'collision_time',
'age',
'analysis_neighborhood',
'supervisor_district',
'data_as_of'
])

In [29]:
df.isnull().sum()

unique_id                0
case_id_fkey             4
latitude                 0
longitude                0
collision_year           0
death_date               0
death_time               0
death_datetime           0
collision_date           0
collision_time           0
collision_datetime       0
location                 0
age                      0
sex                      0
deceased                 0
collision_type           0
street_type              0
on_vz_hin_2017           0
in_coc_2018              0
publish                  0
on_vz_hin_2022           0
in_epa_2021              0
point                    0
analysis_neighborhood    0
supervisor_district      0
police_district          0
data_as_of               0
data_loaded_at           0
dtype: int64

Extract Time Features

In [30]:
df['hour'] = pd.to_datetime(df['collision_time']).dt.hour
df['day'] = df['collision_datetime'].dt.day
df['month'] = df['collision_datetime'].dt.month
df['year'] = df['collision_datetime'].dt.year

/tmp/ipykernel_166/1533958324.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['hour'] = pd.to_datetime(df['collision_time']).dt.hour

Create Severity Target

In [31]:
df['severity'] = df['deceased'].apply(lambda x: 1 if x == True else 0)

Save Cleaned Dataset

In [32]:
df.to_csv("/content/cleaned_crash_data.csv", index=False)